// Generated by https://quicktype.io

export interface AssingnmentFields {
  Name: string;
  Order: number;
  Link: string;
}

export interface AssignmentRecord {
  id: string;
  fields: AssingnmentFields;
  createdTime: string;
  submissionLink?: string;
}
