// Generated by https://quicktype.io

export interface Fields {
  "Chapter Name": string;
  Status: string;
  "Custom Assignments": string[];
  "Chapter Email": string;
  "Omitted Assignments": string[];
}

export interface ChapterRecord {
  id: string;
  fields: Fields;
  createdTime: string;
}
