name: Integrate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Integrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Lint Code Base
        run: npm run lint

      - name: Test Code Base
        run: npm test
