name: Integrate

on:
  push:
    branches: master
  pull_request:

jobs:

  build:
    name: Integrate
    runs-on: ubuntu-latest
    steps:

     - name: Checkout Code
       uses: actions/checkout@v2
       with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
