name: Integrate

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build:
    name: Integrate
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
